# Generated by Django 3.2.12 on 2022-03-06 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continuousproperty',
            name='quantity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='continuousproperty',
            name='units',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='entry',
            name='measurement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', related_query_name='entry', to='database.measurement'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='repository',
            field=models.URLField(default='http://www.github.com', null=True),
        ),
    ]
