# Generated by Django 3.2.12 on 2022-03-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_measurement_setup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='setup',
        ),
        migrations.RemoveField(
            model_name='setupelement',
            name='setup',
        ),
        migrations.AddField(
            model_name='measurement',
            name='setup_element',
            field=models.ManyToManyField(null=True, related_name='setup_elements', to='database.SetupElement'),
        ),
        migrations.DeleteModel(
            name='Setup',
        ),
    ]
