# Generated by Django 3.2.12 on 2022-03-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20220310_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sensoroutput',
            name='measurement',
        ),
        migrations.AddField(
            model_name='sensoroutput',
            name='measurements',
            field=models.ManyToManyField(related_name='sensor_outputs', to='database.Measurement'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='setup_element',
            field=models.ManyToManyField(related_name='setup_elements', to='database.SetupElement'),
        ),
    ]
