# Generated by Django 3.2.12 on 2022-03-10 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20220310_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='setup_element',
        ),
        migrations.AddField(
            model_name='measurement',
            name='setup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', related_query_name='measurement', to='database.setup'),
        ),
        migrations.AddField(
            model_name='setupelement',
            name='setup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setup_elements', to='database.setup'),
        ),
    ]
