# Generated by Django 3.2.12 on 2022-02-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220227_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='organization',
            field=models.CharField(max_length=150, verbose_name='organization'),
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
