# Generated by Django 3.2.12 on 2022-03-06 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20220306_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='object_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='database.objectinstance'),
        ),
    ]
