# Generated by Django 3.2.12 on 2022-03-07 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_measurement_object_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='setup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', related_query_name='measurement', to='database.setup'),
        ),
    ]
